### ISSUE TITLE
Alternate Box Selection methods

### ISSUE THREAD

**Issue by InkDragon** [Slashcash/PCHex-plusplus#6]
Would it be possible to add a way to select a box to the lower screen or set custom buttons for it?

I ask because shoulder buttons have a notoriously high failure rate, and without them it limits a user to only editing the first box.

**Comment by Slashcash** [comment]
I have to admit that the shoulders are pretty incline to broke, i have replaced my 3ds because of them. I'll probably look into that and add a couple of arrows somewhere in the touch screen since i know for a fact that having broken shoulders is somewhat common

**Comment by InkDragon** [comment]
Thank you

**Comment by Slashcash** [comment]
A new mode for shoulderless devices has been added. It draws the buttons in the touch screen and touching them will have the same effect of pressing L/R. To activate the shoulderless button mode you have to boot the program while pressing SELECT.

This mode will be available in the new release, or you can compile the source by yourself starting from the 0ed0b09 commit

**Comment by Slashcash** [comment]
Shoulderless mode is now available in 0.1.3 release
