### ISSUE TITLE
select mode doesn't work

### ISSUE THREAD

**Issue by Filo97** [Slashcash/PCHex-plusplus#9]
on the CIA at least, i don't know in the 3dsx, if i hold select when booting the program, nothing changes.

**Comment by Slashcash** [comment]
Trying pressing select AFTER you selected the game, not before (select your game and then start pressing SELECT)

**Comment by Filo97** [comment]
nope.

**Comment by gocario** [comment]
The Select button is checked as a kDown ([hidKeysDown](hidKeysDown)), you shall check it with a kHeld ([hidKeysHeld](https://github.com/smealum/ctrulib/blob/98fa2f7983d5a31dbc6c446a3478e90294243ebd/libctru/include/3ds/services/hid.h#L102))

**Comment by Slashcash** [comment]
The shoulderless mode not working in cia version has been fixed in 99da52c

Booting the program with the select button pressed will now work even in cia version

**Comment by Filo97** [comment]
Just tried this again. it still does not work for me

**Comment by Slashcash** [comment]
I tried again and it works on my part. Both 3dsx and cia, using 0.1.4 release of course. Can you try again with 0.1.4, booting while pressing SELECT? I can't replicate the bug in any way with the latest release.

**Comment by Filo97** [comment]
i already tried that and i see the normal pchex++ for working shoulder. is there a way to make it autoboot in shoulderless mode? i want to see if that works.
